### ISSUE TITLE
Project Stops Loading when template no longer exists

### ISSUE THREAD

**Issue by fostorial** [fostorial/Legedit2#1]
1. Create a new template
2. Add new card to project
3. Save Project
4. Delete Template

Any cards or decks after the missing template dont load.

**Comment by bloodwurm** [comment]
Repro'ed this issue and actively trying to fix it. Think I've got an easy fix. Stay tuned.

**Comment by bloodwurm** [comment]
Got some fixes ready in a Pull request, enjoy!
