### ISSUE TITLE
Highlight banner too big

### ISSUE THREAD

**Issue by benhurqc** [fostorial/Legedit2#21]
Is there a way to change the black banner behind Cardname and Subname? I'd like it to be not much bigger than the text just like original cards, it hides part of the artwork. Let me know if it's something I can change myself. Thanks!

**Comment by bloodwurm** [comment]
Hi!

Do you mean height-wise or width-wise?

**Comment by bloodwurm** [comment]
- Added the ability to add some bleed of the banner at its top and bottom (use the xml tags bannerextratop and bannerextrabottom). By default, ledEdit2 will assume they respectively value 10 and 15 if not specified. Used the new tags in the Hero templates as an example.

Submitted in https://github.com/bloodwurm/Legedit2/commit/eb154eafb4a57c60b938cda87a74c2471fbd2099
